### PR TITLE
Add models

### PR DESCRIPTION
**Pull request by MartijnBogaert**
Models for activity, validation and annotation added (with inverse relationships as well)

### CODE REVIEW

**Comment by MartijnBogaert** [comment]
@claire-lovisa when backend domain is updated so that an activity has multiple annotations, this should be adjusted here as well

**Comment by claire-lovisa** [comment]
> @claire-lovisa when backend domain is updated so that an activity has multiple annotations, this should be adjusted here as well

Done ! If you approve the backend PR, we can merge both at the same time :)

**Comment by MartijnBogaert** [comment]
@claire-lovisa can you check whether my last commit was necessary? i think it is, but just to be sure

**Comment by claire-lovisa** [comment]
@MartijnBogaert yes ! thank you !

**Pull request merged**
